GO ?= go
RUN_ARGS ?=
GITONE_BOOTSTRAP_USER ?= bootstrap
GITONE_BOOTSTRAP_TOKEN ?= hello

.PHONY: test run

test:
	$(GO) test ./...

run:
	GITONE_BOOTSTRAP_USER="$(GITONE_BOOTSTRAP_USER)" \
	GITONE_BOOTSTRAP_TOKEN="$(GITONE_BOOTSTRAP_TOKEN)" \
	$(GO) run ./cmd/gitone $(RUN_ARGS)
